[tools]
lefthook = "latest"
python = "latest"
ruff = "latest"
uv = "latest"

[env]
_.file = ".env"

[tasks]
"fmt" = "ruff format ."
"lint" = "ruff check --fix ."
"type" = "pyright"
"test" = "pytest"
"all" = { depends = ["fmt", "lint", "type", "test"] }
"watch" = "uv run python main.py"
